###################### Filebeat Configuration  ##############################
# To configure Filebeat, you edit the filebeat.yml configuration file.
# For rpm and deb, this configuration file will be found at /etc/filebeat/filebeat.yml.
# Under Docker, it’s located at /usr/share/filebeat/filebeat.yml
#
# For more available modules and options, please see the filebeat.reference.yml sample
# configuration file at /etc/filebeat/filebeat.reference.yml.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/filebeat/index.html
# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-reference-yml.html
# https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-template.html#load-template-manually
# https://www.elastic.co/guide/en/beats/filebeat/current/configuring-howto-filebeat.html
# https://www.elastic.co/guide/en/beats/filebeat/current/configuration-path.html
# https://www.elastic.co/guide/en/beats/filebeat/current/directory-layout.html
#
# https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields-beat.html
# https://www.elastic.co/guide/en/beats/filebeat/current/exported-fields.html
#
# https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html
# https://www.elastic.co/blog/logstash-metadata
# https://www.elastic.co/guide/en/logstash/current/event-dependent-configuration.html#metadata
#
#=========================== Filebeat inputs ===============================
filebeat.inputs:
- type: log

  # Change to true to enable this input configuration.
  enabled: true

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - "/var/jenkins_home/jobs/*/builds/*/log"

  # Exclude lines. A list of regular expressions to match. It drops the lines that are
  # matching any regular expression from the list.
  #exclude_lines: ['^DBG']

  # Include lines. A list of regular expressions to match. It exports the lines that are
  # matching any regular expression from the list.
  #include_lines: ['^ERR', '^WARN']

  # Exclude files. A list of regular expressions to match. Filebeat drops the files that
  # are matching any regular expression from the list. By default, no files are dropped.
  #exclude_files: ['.gz$']

  # Optional additional fields. These fields can be freely picked
  # to add additional information to the crawled log files for filtering
  #fields:
  #  level: debug
  #  review: 1

  ### Multiline options
  # configure multiline for lines without a starting date (https://www.elastic.co/guide/en/beats/filebeat/master/_examples_of_multiline_configuration.html#_java_stack_traces)
  multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}[T ]'
  multiline.negate: true
  multiline.match: after

#============================= Filebeat modules ===============================
filebeat.config:
  prospectors:
    path: ${path.config}/prospectors.d/*.yml
    reload.enabled: false
  modules:
    # Glob pattern for configuration loading
    path: ${path.config}/modules.d/*.yml
    # Set to true to enable config reloading
    reload.enabled: false
    # Period on which files under path should be checked for changes
    #reload.period: 10s

#================================ General =====================================

# The name of the shipper that publishes the network data. It can be used to group
# all the transactions sent by a single shipper in the web interface.
name: filebeat-gitlab-jenkins

# The tags of the shipper are included in their own field with each
# transaction published.
#tags: ["service-X", "web-tier"]

# Optional fields that you can specify to add additional information to the
# output.
fields:
  env: prod
  cluster: devops-48

#================================ Outputs =====================================

# Configure what output to use when sending the data collected by the beat.

#----------------------------- Logstash output --------------------------------
output.logstash:
  # The Logstash hosts
  hosts: ["logstash:5044"]
  #index: 'filebeat_prod_devops'

  # Optional SSL. By default is off.
  # List of root certificates for HTTPS server verifications
  #ssl.certificate_authorities: ["/etc/pki/root/ca.pem"]

  # Certificate for SSL client authentication
  #ssl.certificate: "/etc/pki/client/cert.pem"

  # Client Certificate Key
  #ssl.key: "/etc/pki/client/cert.key"
